version: "3.7"
services:
    react-app:
        #build: .
        build:
          context: .
          dockerfile: Dockerfile.dev
        ports:
          - 300:3000
        volumes:
          - ./src:/app/src:ro
        environment:
          - REACT_APP_NAME=app-dev
          - CHOKIDAR_USEPOLLING=true
        # env_file:
          # - ./.env

#docker-compose --help   
#docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d --build
#docker-compose -f docker-compose.yml -f docker-compose-dev.yml down   
#docker-compose build
#docker-compose up, up -d, up -d --build,start, stop, down
# default image name is: foderName_serviceName => my-app_react-app
# default containe name is: foderName_serviceName_numeric => my-app_react-app_1
